# Generated by Django 5.0 on 2024-07-16 18:33

import django.db.models.deletion
from django.db import migrations, models

def create_initial_data(apps, schema_editor):
    # Obtener los modelos
    Ubicaciones = apps.get_model('medicos', 'Ubicaciones')
    Departamentos = apps.get_model('medicos', 'Departamentos')
    Especialidades = apps.get_model('medicos', 'Especialidades')
    Medicos = apps.get_model('medicos', 'Medicos')
    Horario_medicos = apps.get_model('medicos', 'Horario_medicos')

    # Crear ubicaciones
    ubicacion1 = Ubicaciones.objects.create(nombre='Ubicacion 1', descripcion='Descripcion 1')
    ubicacion2 = Ubicaciones.objects.create(nombre='Ubicacion 2', descripcion='Descripcion 2')

    # Crear departamentos
    departamento1 = Departamentos.objects.create(nombre='Departamento 1', descripcion='Descripcion 1', ubicacionID=ubicacion1)
    departamento2 = Departamentos.objects.create(nombre='Departamento 2', descripcion='Descripcion 2', ubicacionID=ubicacion2)

    # Crear especialidades
    especialidad1 = Especialidades.objects.create(nombre='Especialidad 1', descripcion='Descripcion 1', departamentoID=departamento1)
    especialidad2 = Especialidades.objects.create(nombre='Especialidad 2', descripcion='Descripcion 2', departamentoID=departamento2)

    # Crear médicos
    medico1 = Medicos.objects.create(nombre='Juan', apellido='Perez', dni='12345678', especialidadID=especialidad1, telefono='1234567890', email='juan.perez@example.com')
    medico2 = Medicos.objects.create(nombre='Ana', apellido='Gomez', dni='87654321', especialidadID=especialidad2, telefono='0987654321', email='ana.gomez@example.com')

    # Crear horarios de médicos
    Horario_medicos.objects.create(medicoID=medico1, dia='Lunes', hora_inicio='09:00:00', hora_fin='17:00:00', especialidadID=especialidad1, departamentoID=departamento1)
    Horario_medicos.objects.create(medicoID=medico2, dia='Martes', hora_inicio='10:00:00', hora_fin='18:00:00', especialidadID=especialidad2, departamentoID=departamento2)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('ubicacionID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('medicoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_medicos',
            fields=[
                ('horarioID', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos')),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='ubicacionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.ubicaciones'),
        ),
        migrations.RunPython(
            code=create_initial_data,
        ),
    ]