# Generated by Django 5.0 on 2024-11-05 22:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('ubicacionID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('dni', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=125, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('last_logout', models.DateField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('medicoID', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='medic/')),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
                ('groups', models.ManyToManyField(blank=True, related_name='medicos_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='medicos_permissions', to='auth.permission')),
            ],
            options={
                'permissions': [('view_panel_medic', 'Can view panel medic')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicioID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_medicos',
            fields=[
                ('horarioID', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=12)),
                ('hora', models.TimeField()),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos')),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
                ('servicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='ubicacionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.ubicaciones'),
        ),
    ]
