# Generated by Django 5.0 on 2024-08-16 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('precioID', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
            ],
        ),
    ]
