# Generated by Django 5.0.6 on 2024-08-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_precios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicioID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidades')),
            ],
        ),
        migrations.DeleteModel(
            name='Precios',
        ),
    ]
