# Generated by Django 5.0.6 on 2024-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_servicios_delete_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
