# Generated by Django 5.0 on 2024-10-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_alter_servicios_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario_medicos',
            old_name='hora_fin',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='horario_medicos',
            name='hora_inicio',
        ),
    ]
