# Generated by Django 5.0 on 2024-10-22 19:56

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_horario_medicos_servicioid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='medicos',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='medicos',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
