# Generated by Django 5.0 on 2024-10-22 20:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medicos', '0008_alter_medicos_options_alter_medicos_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='usuarios_ptr',
        ),
        migrations.AddField(
            model_name='medicos',
            name='apellido',
            field=models.CharField(default='medico_sin_apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='medicos',
            name='contraseña',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default='2024-02-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicos',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='medicos_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='imagen',
            field=models.ImageField(blank=True, default='medic/profile_<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.png', null=True, upload_to='medic/'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='last_logout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='nombre',
            field=models.CharField(default='medico_sin_nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='medicos',
            name='password',
            field=models.CharField(default=1234321, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicos',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='medicos_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='username',
            field=models.CharField(default='pepe', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
