# Generated by Django 5.0 on 2024-10-29 01:33

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_alter_medicos_options_remove_medicos_usuarios_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='medicos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
