# Generated by Django 5.0 on 2024-10-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0010_remove_medicos_apellido_remove_medicos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_medicos',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=12),
        ),
    ]
