# Generated by Django 5.0 on 2024-11-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0011_alter_horario_medicos_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'permissions': [('view_panel_medic', 'Can view panel medic')]},
        ),
    ]
