# Generated by Django 5.0 on 2024-07-31 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('citaID', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=25)),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos')),
                ('horarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.horario_medicos')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('TurnoID', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=25)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('citaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
