# Generated by Django 5.0 on 2024-07-16 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('citaID', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('TurnoID', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
