# Generated by Django 5.0 on 2024-10-23 00:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0007_horario_medicos_servicioid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_created', models.DateField(auto_now=True)),
                ('citaID', models.AutoField(primary_key=True, serialize=False)),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos')),
                ('horarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.horario_medicos')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
                ('servicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.servicios')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CajaTurnero',
            fields=[
                ('cajaID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('ingreso', models.FloatField(default=0)),
                ('egreso', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('estado', models.CharField(max_length=25)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('horario_transaccion', models.TimeField(default=django.utils.timezone.now)),
                ('citaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCaja',
            fields=[
                ('detalleID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField(default=0)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('horario_transaccion', models.TimeField(default=django.utils.timezone.now)),
                ('cajaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.cajaturnero')),
                ('servicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_created', models.DateField(auto_now=True)),
                ('TurnoID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_limt', models.DateField(default=django.utils.timezone.now)),
                ('citaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
                ('servicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.servicios')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
