# Generated by Django 5.0 on 2024-07-16 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnero', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='departamentoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departamentos'),
        ),
        migrations.AddField(
            model_name='citas',
            name='horarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.horario_medicos'),
        ),
        migrations.AddField(
            model_name='citas',
            name='medicoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.medicos'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='citaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
