# Generated by Django 5.0 on 2024-08-16 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citas',
            name='fecha_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='fecha_limt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CajaTurnero',
            fields=[
                ('cajaID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('ingreso', models.FloatField(default=0)),
                ('egreso', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('estado', models.CharField(max_length=25)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('horario_transaccion', models.TimeField(default=django.utils.timezone.now)),
                ('citaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCaja',
            fields=[
                ('detalleID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField(default=0)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('horario_transaccion', models.TimeField(default=django.utils.timezone.now)),
                ('cajaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.cajaturnero')),
                ('servicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
            ],
        ),
    ]
