# Generated by Django 5.0 on 2024-07-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('turnero', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='departamentoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.departamentos'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='horarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.horario_medicos'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='medicoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
    ]
