# Generated by Django 5.0.6 on 2024-08-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_servicios_delete_precios'),
        ('turnero', '0002_citas_fecha_citas_fecha_created_citas_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='servicioID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.servicios'),
            preserve_default=False,
        ),
    ]
