# Generated by Django 5.0 on 2024-07-19 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('turnero', '0003_alter_citas_departamentoid_alter_citas_horarioid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='medicoID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='motivo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
