# Generated by Django 5.0 on 2024-09-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_citas_servicioid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='servicioID',
        ),
    ]
