# Generated by Django 5.0 on 2024-10-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_horario_medicos_servicioid'),
        ('turnero', '0003_basemodelturnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='servicioID',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='medicos.servicios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='servicioID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.servicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citas',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='fecha_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='BaseModelTurnos',
        ),
    ]
