# Generated by Django 5.0 on 2024-10-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0008_alter_medicos_options_alter_medicos_managers_and_more'),
        ('turnero', '0004_citas_servicioid_turnos_servicioid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='medicoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_medic', to='medicos.medicos'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='medicoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_medic', to='medicos.medicos'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
