# Generated by Django 5.0 on 2024-07-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_alter_citas_departamentoid_alter_citas_horarioid_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='ubicacionID',
        ),
        migrations.RemoveField(
            model_name='horario_medicos',
            name='departamentoID',
        ),
        migrations.RemoveField(
            model_name='especialidades',
            name='departamentoID',
        ),
        migrations.RemoveField(
            model_name='horario_medicos',
            name='especialidadID',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='especialidadID',
        ),
        migrations.RemoveField(
            model_name='horario_medicos',
            name='medicoID',
        ),
        migrations.DeleteModel(
            name='Ubicaciones',
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.DeleteModel(
            name='Horario_medicos',
        ),
        migrations.DeleteModel(
            name='Medicos',
        ),
    ]
