# Generated by Django 5.0 on 2024-10-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(default='usuario_sin_apellido', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuarios_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, default='user/profile_<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.png', null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='usuario_sin_nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permissions', to='auth.permission'),
        ),
    ]
