# Generated by Django 5.0 on 2024-09-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
