# Generated by Django 5.0 on 2024-09-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuarios_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, default='user/profile_<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.png', null=True, upload_to='user/'),
        ),
    ]
