# Generated by Django 5.0 on 2024-07-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_departamentos_ubicacionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
