# Generated by Django 5.0 on 2024-10-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuarios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
