# Generated by Django 5.0 on 2024-11-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuarios_options_remove_usuarios_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSociales',
            fields=[
                ('obraID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('desciption', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='obraID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.obrasociales'),
        ),
    ]
