# Generated by Django 5.0 on 2024-11-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_obrasociales_usuarios_obraid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObraSociales',
            new_name='ObrasSociales',
        ),
    ]
