# Generated by Django 5.0 on 2024-10-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_blacklisttokens_id_blacklisttokens_tokenid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklisttokens',
            name='DB',
        ),
    ]
