# Generated by Django 5.0 on 2024-10-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_blacklisttokens_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisttokens',
            name='tokenUUID',
            field=models.UUIDField(default=1234567, verbose_name='Token_UUID'),
            preserve_default=False,
        ),
    ]
